version: "3.9"

networks:
  mgmt-net:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.3.0/24"

services:
  spine-router:
    image: frrouting/frr
    container_name: spine-router
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      mgmt-net:
        ipv4_address: "10.10.3.1"
    restart: unless-stopped
    volumes:
      - /etc/frr:/etc/frr

  netbox:
    image: netboxcommunity/netbox:latest
    container_name: netbox
    networks:
      mgmt-net:
        ipv4_address: "10.10.3.11"
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SUPERUSER_NAME=admin
      - SUPERUSER_EMAIL=admin@hpe-twin.local
      - SUPERUSER_PASSWORD=admin
      - ALLOWED_HOSTS=*
      - DB_HOST=localhost
      - DB_NAME=netbox
      - DB_USER=netbox
      - DB_PASSWORD=netbox
      - SECRET_KEY=hpe-digital-twin-secret-key-change-in-prod

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    networks:
      mgmt-net:
        ipv4_address: "10.10.3.12"
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=none
    volumes:
      - neo4j-data:/data

  python-app:
    image: python:3.11
    container_name: python-app
    command: sleep infinity
    networks:
      mgmt-net:
        ipv4_address: "10.10.3.13"
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - /opt/python-app:/app
    working_dir: /app

volumes:
  neo4j-data:
